server:
  port: 8761
eureka:
  client:
    #  表示是否将自己注册到Eureka Servcer。
    register-with-eureka: false
    #  表示是否从Eureka Server获取注册信息
    fetchRegistry: false
    serviceUrl:
      #  设置Eureka Server交互的地址
      defaultZone: http://admin:admin@localhost:8761/eureka/
spring:
  application:
    name: atcc-serviceplatform-discovery
  security:
    user:
      name: admin
      password: admin

