server:
  port: 9080

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: atcc-serviceplatform-gateway
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      #location: D:\\home\\neuroot\\profilePhoto
      location: /project/atcc-serviceplatform/profilePhoto
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  routes:
    atcc-serviceplatform-useradapter: /atcc-serviceplatform-useradapter/**
    atcc-serviceplatform-authentication: /atcc-serviceplatform-authentication/**
    atcc-serviceplatform-oauth2: /atcc-serviceplatform-oauth2/**
    atcc-serviceplatform-smarthomeadapter: /atcc-serviceplatform-smarthomeadapter/**
    atcc-serviceplatform-caradapter: /atcc-serviceplatform-caradapter/**
    atcc-serviceplatform-messageadapter: /atcc-serviceplatform-messageadapter/**



      #面向服务路由
      #customSensitiveHeaders: true
      #sensitiveHeaders:

      #path:
      #serviceId:

    api-a-url:
      path: /api-a-url
      url: http://localhost:8080/
  AccessFilter:
    pre:
      disable: false
  SendErrorFilter:
    post:
      disable: true

  #retryable: false


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutIntMilliseconds: 120000

jwt:
  SECRET_BAIDU: qweRTYuioasdFGHjklzxcVBNmradio
  SECRET_HU: qweRTYuioasdFGHjklzxcVBNmhu
  SECRET_AUTO: qweRTYuioasdFGHjklzxcVBNmauto
  SECRET_JD: qweRTYuioasdFGHjklzxcVBNmjd
  CODE_EXPIREIN: 300
  REFRESH_TOKEN_EXPIREIN: 2592000
  ACCESS_TOKEN_EXPIREIN: 7200
  AUTHORITY_LIST: scp01001 scp01002 scp01003 scp02001 read

